edition = "2021"
max_width = 100
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"

# Stable options only
reorder_imports = true
reorder_modules = true

imports_granularity = "Module"
